# Copyright the Hyperledger Fabric contributors. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: Scheduled build

on:
  schedule:
    - cron: "5 2 * * *"
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        checkout-ref:
          - main
          - release-2.5
    uses: ./.github/workflows/test.yaml
    with:
      checkout-ref: ${{ matrix.checkout-ref }}
