name: "Security vulnerability scan"

on:
  schedule:
    - cron: "55 2 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  latest-release-version:
    name: Get latest release tag
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.tag-name.outputs.value }}
    steps:
      - id: tag-name
        run: echo "value=$(curl --location --silent --fail "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest" | jq --raw-output '.tag_name')" >> "${GITHUB_OUTPUT}"

  scan:
    name: Scan ${{ needs.latest-release-version.outputs.tag_name }}
    needs: latest-release-version
    uses: ./.github/workflows/scan.yaml
    with:
      ref: ${{ needs.latest-release-version.outputs.tag_name }}
